# Generated by Django 4.2 on 2025-04-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá bán')),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, '0 sao'), (1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=0, verbose_name='Sao đánh giá')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh sản phẩm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
