# Generated by Django 4.2 on 2025-06-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_products_delete_student_product_descrip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descrip',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
