# Generated by Django 4.2 on 2025-07-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descrip',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
